* Evaluation

** Goals

Show that deep learning methods reduce the errors in the intracraneal cavity estimation in different scenarios:

1. Show that Deep learning methods are more accurate with respect to manual brain annotations.
2. Show that the Deep learning methods increases the reproducibility of the intracraneal cavity for the same patient scanned in different machines (Siemens, Phillips and GE)
3. Show that the Deep learning methods increases the reproducibility of the intracraneal cavity for the same patient with scan/rescan for different machines (Siemens, Phillips and GE)

** Data
- Calgary-Campinas dataset: 351 scans from three different scanners (Siemens, Phillips and GE). This dataset contains silver-standard masks computed from different state-of-the-art methods. This dataset has been used to train the CNN method.
  - 12 cases also incorporate a manual brainmask that can be used to evaluate the performance of the method.
- LBPA40 dataset: 40 images with manual brain annotations
- Biomarkem project:
  - 15 healthy subjects scanned at three different scanners (Siemens, Phillips and GE) with scan-rescan.
  - 10 MS patients scanned at at three different scanners (Siemens, Phillips and GE) with scan-rescan.

** Experiments
- EXPERIMENT 1: Compare our CNN against other state-of-the-art methods on the Calgary-Campinas dataset (12 scans)
- EXPERIMENT 2: Compare our CNN against other state-of-the-art methods on the LPBA40 dataset (40 scans)
- EXPERIMENT 3: Compare our CNN against other state-of-the-art methods on the Biomarkem subjects and patients with scan/rescan for each of the scanners.
- EXPERIMENT 4: Compare our CNN against other state-of-the-art methods on the Biomarkem subjects and patients scanned at differnt machines and compare the differences between scanners.

** Strategy
The paper should be targeted for the clinical audience, showing that novel methods such as Deep Learning's  help to reduce the errors in the skull quantification, which has a lot of potential benefits in other subsequent tasks such as tissue and lesion segmentation or brain atrophy quantification.

*** How to present the results:

- Show that the proposed method works very well in practice when compared with other methods (EXPERIMENTS 1, 2), so it's validated for the rest of the experiments
- Show that the proposed method is more robust in scan / rescan of the same patient (EXPERIMENT 3)
  - Present the results for each of the three scanners.
- Show that the proposed method is more robust showing the intracraneal cavity of the same patient across scanners (EXPERIMENT 4).

*** Things to do:
- Find missing scans in biomarkem
- Run state-of-the-art methods in the biomarkem dataset
- Run the CONSNET method (deep learning) in the biomarkem dataset
- Compare and update the results with the new data
- Write the paper

** Resources
- PARIETAL repository
- Excel with some results
  - https://docs.google.com/spreadsheets/d/1SXPm4tZyM1ktAdAmt4K3adv6y-o08Qav5BPuMGAS8HA/edit?usp=sharing
- Biomarkem dataset with some of the experiments already performed
